version: '3.3'
services:
  api:
    image: lumir/hydra-data-squid:latest
    command:
      - sqd
      - serve:prod
    environment:
      DB_HOST: db
      DB_NAME: squid
      DB_PASS: postgres
      DB_PORT: '5432'
      GQL_PORT: '4350'
      ARCHIVE: https://hydradx-rococo-firesquid.play.hydration.cloud/graphql
      RPC: wss://hydradx-rococo-rpc.play.hydration.cloud
    networks:
      - default
    logging:
      driver: json-file
    deploy:
      replicas: 3
      labels:
        traefik.http.routers.hrds.rule: Host(`hydra-rococo-data-squid.play.hydration.cloud`)
        traefik.http.routers.hrds.tls: 'true'
        traefik.http.routers.hrds.tls.certresolver: myresolver
        traefik.http.services.hrds.loadbalancer.server.port: '4350'
  db:
    image: postgres:15
    environment:
      POSTGRES_DB: squid
      POSTGRES_PASSWORD: postgres
    networks:
      - default
    logging:
      driver: json-file
  processor:
    image: lumir/hydra-data-squid:latest
    command:
      - sqd
      - process:prod
    environment:
      DB_HOST: db
      DB_NAME: squid
      DB_PASS: postgres
      DB_PORT: '5432'
    networks:
      - default
    logging:
      driver: json-file
networks:
  default:
    driver: overlay
